"""Test setup: isolated SQLite DB, mock local LLM, immediate (inline) job execution."""
from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

os.environ["POLY_MOCK_LLM"] = "1"
os.environ["POLY_JOBS_IMMEDIATE"] = "1"
os.environ["POLY_OLLAMA_URL"] = "http://127.0.0.1:1"  # nothing listens here → detection sees Ollama down
os.environ["POLY_OPENAI_COMPAT_URLS"] = ""

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="session")
def data_dir(tmp_path_factory) -> Path:
    d = tmp_path_factory.mktemp("polydata")
    os.environ["POLY_DATA_DIR"] = str(d)
    os.environ["POLY_DATABASE_URL"] = f"sqlite:///{d / 'test.db'}"
    from poly.config import reset_settings_cache

    reset_settings_cache()
    return d


@pytest.fixture(scope="session")
def engine(data_dir):
    from poly.db import configure_engine, init_db

    eng = configure_engine(os.environ["POLY_DATABASE_URL"])
    init_db(eng)
    return eng


@pytest.fixture()
def db(engine):
    from poly.db import get_session_factory

    session = get_session_factory()()
    yield session
    session.rollback()
    session.close()


@pytest.fixture(scope="session")
def seeded(engine):
    """Principles seeded from the real knowledge file + mock model registered."""
    from poly.db import session_scope
    from poly.providers.registry import detect_and_register
    from poly.services.principles import import_markdown, list_principles
    from poly.services.search import embed_entity

    with session_scope() as s:
        import_markdown(s, FIXTURES.parent.parent.parent / "knowledge" / "political_operating_system.md")
        detect_and_register(s)
        for p in list_principles(s):
            embed_entity(s, "principle", p)
    return True


@pytest.fixture(scope="session")
def ingested(engine, seeded) -> dict:
    """Ingest fixture feeds A then B once; returns the per-feed stats for assertions."""
    from poly.db import session_scope
    from poly.providers.news.rss import parse_feed_bytes
    from poly.services.ingest import ingest_raw_articles

    out = {}
    with session_scope() as s:
        out["a"] = ingest_raw_articles(s, parse_feed_bytes((FIXTURES / "sample_feed_a.xml").read_bytes()), lookback_days=10000)
        out["b"] = ingest_raw_articles(s, parse_feed_bytes((FIXTURES / "sample_feed_b.xml").read_bytes()), lookback_days=10000)
    return out


@pytest.fixture(scope="session")
def client(engine, seeded, ingested):
    from fastapi.testclient import TestClient

    from poly.main import create_app

    app = create_app()
    with TestClient(app) as c:
        yield c


@pytest.fixture(scope="session")
def test_video(data_dir) -> Path:
    """A 30-second synthetic video with a tone track, generated by FFmpeg (no personal media)."""
    out = data_dir / "videos" / "sample_talk.mp4"
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-f", "lavfi", "-i", "testsrc=size=1280x720:rate=30", "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=16000", "-t", "30", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", str(out)],
        check=True,
    )
    return out


def fixture_transcript() -> list[dict]:
    """Realistic word-timed transcript covering 30s, used for clip + caption tests."""
    text = (
        "Here's why CEO pay keeps rising even when the company doesn't. Most people think boards set pay based on performance. "
        "Actually, the system works through peer benchmarking, which means every company wants to pay above the median. "
        "That is mathematically impossible, so pay ratchets upward year after year. The point is the incentive structure, not the individuals. "
        "So what would I change? Longer vesting periods and real clawbacks would align executives with long-term shareholders and employees."
    )
    words = text.split()
    dur = 29.0 / len(words)
    segs, cur, start = [], [], 0.5
    for i, w in enumerate(words):
        s = 0.5 + i * dur
        cur.append({"w": w, "s": round(s, 2), "e": round(s + dur * 0.9, 2)})
        if w.endswith((".", "?")) or i == len(words) - 1:
            segs.append({"start": start, "end": round(s + dur, 2), "text": " ".join(x["w"] for x in cur), "words": cur})
            cur, start = [], round(s + dur, 2)
    return segs
