"""video_projects (faceless studio)

Revision ID: 2dee679688b2
Revises: 47ad95240c21
Create Date: 2026-08-30 23:45:37.722892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import poly.models


# revision identifiers, used by Alembic.
revision: str = '2dee679688b2'
down_revision: Union[str, Sequence[str], None] = '47ad95240c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('content_item_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=30), nullable=False),
    sa.Column('target_seconds', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('voice_mode', sa.String(length=10), nullable=False),
    sa.Column('tts_voice', sa.String(length=80), nullable=False),
    sa.Column('music_path', sa.String(length=2000), nullable=False),
    sa.Column('music_recommendation', sa.String(length=300), nullable=False),
    sa.Column('scenes', sa.JSON(), nullable=False),
    sa.Column('previous_scenes', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('brand_overrides', sa.JSON(), nullable=False),
    sa.Column('render_status', sa.String(length=20), nullable=False),
    sa.Column('render_path', sa.String(length=2000), nullable=False),
    sa.Column('render_error', sa.Text(), nullable=True),
    sa.Column('generation_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_projects_content_item_id'), ['content_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_projects_content_item_id'))

    op.drop_table('video_projects')
    # ### end Alembic commands ###
