"""initial schema

Revision ID: 47ad95240c21
Revises: 
Create Date: 2026-08-30 01:38:35.278650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import poly.models


# revision identifiers, used by Alembic.
revision: str = '47ad95240c21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('working_titles', sa.JSON(), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('vector', poly.models.VectorType(), nullable=True),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'chunk_index', name='uq_embedding_chunk')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_embeddings_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_entity_type'), ['entity_type'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('cloud_override_allowed', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('local_models',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('runtime', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('fallback_model_id', sa.String(length=32), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('last_ok_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('locality', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['local_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'runtime', 'endpoint', name='uq_local_model')
    )
    op.create_table('principles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('current_position', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('principles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_principles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_principles_status'), ['status'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('ideology', sa.String(length=50), nullable=True),
    sa.Column('reliability_notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_domain'), ['domain'], unique=True)

    op.create_table('stories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_updated', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('primary_sources', sa.JSON(), nullable=False),
    sa.Column('unresolved_questions', sa.JSON(), nullable=False),
    sa.Column('competing_interpretations', sa.JSON(), nullable=False),
    sa.Column('content_potential', sa.JSON(), nullable=False),
    sa.Column('recommended_format', sa.String(length=40), nullable=False),
    sa.Column('dashboard_action', sa.String(length=30), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('analysis_source', sa.String(length=40), nullable=False),
    sa.Column('analyzed_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_dashboard_action'), ['dashboard_action'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_relevance_score'), ['relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_status'), ['status'], unique=False)

    op.create_table('video_folders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=2000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('recursive', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('book_chapters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('book_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_chapters_book_id'), ['book_id'], unique=False)

    op.create_table('counterarguments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('principle_id', sa.String(length=32), nullable=False),
    sa.Column('argument', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('unresolved_questions', sa.JSON(), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counterarguments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterarguments_principle_id'), ['principle_id'], unique=False)

    op.create_table('feeds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('last_fetched_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('fetch_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'query', name='uq_feed_url_query')
    )
    op.create_table('principle_revisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('principle_id', sa.String(length=32), nullable=False),
    sa.Column('old_position', sa.Text(), nullable=False),
    sa.Column('new_position', sa.Text(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('reason_for_change', sa.Text(), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('principle_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_principle_revisions_principle_id'), ['principle_id'], unique=False)

    op.create_table('story_principle_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=False),
    sa.Column('principle_id', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'principle_id', name='uq_story_principle')
    )
    with op.batch_alter_table('story_principle_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_principle_links_principle_id'), ['principle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_principle_links_story_id'), ['story_id'], unique=False)

    op.create_table('think_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=True),
    sa.Column('principle_id', sa.String(length=32), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('principle_ids_considered', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('think_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_think_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_think_sessions_story_id'), ['story_id'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('folder_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=2000), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('codec', sa.String(length=50), nullable=False),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('file_created_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('file_modified_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('transcript_status', sa.String(length=20), nullable=False),
    sa.Column('transcript_provider', sa.String(length=60), nullable=False),
    sa.Column('transcript_language', sa.String(length=10), nullable=False),
    sa.Column('transcript_error', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('people', sa.JSON(), nullable=False),
    sa.Column('key_moments', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('missing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['video_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_transcript_status'), ['transcript_status'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('canonical_url', sa.String(length=2000), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('title_simhash', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('publication', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('feed_id', sa.String(length=32), nullable=True),
    sa.Column('story_id', sa.String(length=32), nullable=True),
    sa.Column('published_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('duplicate_of_id', sa.String(length=32), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_title_simhash'), ['title_simhash'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_url_hash'), ['url_hash'], unique=True)

    op.create_table('clips',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('why_it_works', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('render_path', sa.String(length=2000), nullable=False),
    sa.Column('render_settings', sa.JSON(), nullable=False),
    sa.Column('render_error', sa.Text(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clips_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_video_id'), ['video_id'], unique=False)

    op.create_table('position_briefs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('think_session_id', sa.String(length=32), nullable=True),
    sa.Column('story_id', sa.String(length=32), nullable=True),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('position', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('governing_principle_id', sa.String(length=32), nullable=True),
    sa.Column('governing_principle_text', sa.Text(), nullable=False),
    sa.Column('strongest_for', sa.Text(), nullable=False),
    sa.Column('strongest_against', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('factual_assumptions', sa.JSON(), nullable=False),
    sa.Column('unresolved_questions', sa.JSON(), nullable=False),
    sa.Column('policy_mechanisms', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_principle_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('approved_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_principle_id'], ['principles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['governing_principle_id'], ['principles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['think_session_id'], ['think_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_briefs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_briefs_story_id'), ['story_id'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('words', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_segments_video_id'), ['video_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=False),
    sa.Column('article_id', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('supporting_passage', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('publication', sa.String(length=200), nullable=False),
    sa.Column('is_primary_source', sa.Boolean(), nullable=False),
    sa.Column('primary_source_url', sa.String(length=2000), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_story_id'), ['story_id'], unique=False)

    op.create_table('content_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('format', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=True),
    sa.Column('principle_ids', sa.JSON(), nullable=False),
    sa.Column('position_brief_id', sa.String(length=32), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('package', sa.JSON(), nullable=False),
    sa.Column('source_video_id', sa.String(length=32), nullable=True),
    sa.Column('clip_id', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('publish_date', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('fact_check_status', sa.String(length=30), nullable=False),
    sa.Column('fact_check_override_reason', sa.Text(), nullable=False),
    sa.Column('substantive_value', sa.Float(), nullable=True),
    sa.Column('approved_at', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('generation_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_brief_id'], ['position_briefs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_items_format'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_story_id'), ['story_id'], unique=False)

    op.create_table('story_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=False),
    sa.Column('article_id', sa.String(length=32), nullable=True),
    sa.Column('occurred_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_events_story_id'), ['story_id'], unique=False)

    op.create_table('supporting_evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('principle_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('publication_date', poly.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reliability', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('article_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supporting_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supporting_evidence_principle_id'), ['principle_id'], unique=False)

    op.create_table('book_notes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('book_id', sa.String(length=32), nullable=True),
    sa.Column('chapter_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=True),
    sa.Column('principle_id', sa.String(length=32), nullable=True),
    sa.Column('content_item_id', sa.String(length=32), nullable=True),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('article_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['book_id'], ['book_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['book_chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_notes_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_notes_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('content_metrics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('content_item_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('recorded_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('watch_time_seconds', sa.Float(), nullable=False),
    sa.Column('retention_pct', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('completion_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_metrics_content_item_id'), ['content_item_id'], unique=False)

    op.create_table('fact_check_claims',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('content_item_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_check_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_check_claims_content_item_id'), ['content_item_id'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('path', sa.String(length=2000), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('content_item_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_notes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('story_id', sa.String(length=32), nullable=True),
    sa.Column('principle_id', sa.String(length=32), nullable=True),
    sa.Column('content_item_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', poly.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_notes_principle_id'), ['principle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_notes_story_id'), ['story_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_notes_story_id'))
        batch_op.drop_index(batch_op.f('ix_research_notes_principle_id'))

    op.drop_table('research_notes')
    op.drop_table('images')
    with op.batch_alter_table('fact_check_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_check_claims_content_item_id'))

    op.drop_table('fact_check_claims')
    with op.batch_alter_table('content_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_metrics_content_item_id'))

    op.drop_table('content_metrics')
    with op.batch_alter_table('book_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_notes_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_book_notes_book_id'))

    op.drop_table('book_notes')
    with op.batch_alter_table('supporting_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supporting_evidence_principle_id'))

    op.drop_table('supporting_evidence')
    with op.batch_alter_table('story_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_events_story_id'))

    op.drop_table('story_events')
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_story_id'))
        batch_op.drop_index(batch_op.f('ix_content_items_status'))
        batch_op.drop_index(batch_op.f('ix_content_items_publish_date'))
        batch_op.drop_index(batch_op.f('ix_content_items_parent_id'))
        batch_op.drop_index(batch_op.f('ix_content_items_format'))

    op.drop_table('content_items')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_story_id'))

    op.drop_table('claims')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_video_id'))

    op.drop_table('transcript_segments')
    with op.batch_alter_table('position_briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_briefs_story_id'))
        batch_op.drop_index(batch_op.f('ix_position_briefs_status'))

    op.drop_table('position_briefs')
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clips_video_id'))
        batch_op.drop_index(batch_op.f('ix_clips_status'))
        batch_op.drop_index(batch_op.f('ix_clips_score'))

    op.drop_table('clips')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_url_hash'))
        batch_op.drop_index(batch_op.f('ix_articles_title_simhash'))
        batch_op.drop_index(batch_op.f('ix_articles_story_id'))
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_articles_content_hash'))

    op.drop_table('articles')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_transcript_status'))
        batch_op.drop_index(batch_op.f('ix_videos_folder_id'))

    op.drop_table('videos')
    with op.batch_alter_table('think_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_think_sessions_story_id'))
        batch_op.drop_index(batch_op.f('ix_think_sessions_status'))

    op.drop_table('think_sessions')
    with op.batch_alter_table('story_principle_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_principle_links_story_id'))
        batch_op.drop_index(batch_op.f('ix_story_principle_links_principle_id'))

    op.drop_table('story_principle_links')
    with op.batch_alter_table('principle_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_principle_revisions_principle_id'))

    op.drop_table('principle_revisions')
    op.drop_table('feeds')
    with op.batch_alter_table('counterarguments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterarguments_principle_id'))

    op.drop_table('counterarguments')
    with op.batch_alter_table('book_chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_chapters_book_id'))

    op.drop_table('book_chapters')
    op.drop_table('video_folders')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_status'))
        batch_op.drop_index(batch_op.f('ix_stories_slug'))
        batch_op.drop_index(batch_op.f('ix_stories_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_stories_last_updated'))
        batch_op.drop_index(batch_op.f('ix_stories_first_seen'))
        batch_op.drop_index(batch_op.f('ix_stories_dashboard_action'))

    op.drop_table('stories')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_domain'))

    op.drop_table('sources')
    op.drop_table('settings')
    with op.batch_alter_table('principles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_principles_status'))
        batch_op.drop_index(batch_op.f('ix_principles_category'))

    op.drop_table('principles')
    op.drop_table('local_models')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_entity_type'))
        batch_op.drop_index(batch_op.f('ix_embeddings_entity_id'))
        batch_op.drop_index('ix_embeddings_entity')

    op.drop_table('embeddings')
    op.drop_table('book_projects')
    # ### end Alembic commands ###
